### ISSUE TITLE
Requirements error

### ISSUE THREAD

**Issue by Ectalite** [Data-Horde/gdrivac#7]
I have a MacBook Pro with macOS Catalina (10.15.7) and one module for the script wasn't in the requirements:
- colorama
After I installed, the help command worked.
Could you please add it to the requirements file ?

PS: On macOS python and python3 are two separated commands and not using python3 would bring other errors, so it would be better if you write this as an observation in the readme.

**Comment by madprogramer** [comment]
Huh, I guess those color codes might have been too fancy after all. Alright, patching it in!
